version: '3.9'
services:
  customer-service:
    image: customer_image
    container_name: authentication
    build: ./
    restart: always
    networks:
      - mynetwork
    ports:
      - 8085:8085
    depends_on:
      - mongoService


  mongoService:
    image: mongo:latest
    container_name: mongoService
    networks:
      - mynetwork
    ports:
      - 8090:8090



networks:
  mynetwork:
    driver: bridge